# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'professor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 585)
        self.tableProfessor = QtWidgets.QTableWidget(Form)
        self.tableProfessor.setGeometry(QtCore.QRect(40, 20, 601, 331))
        self.tableProfessor.setRowCount(3)
        self.tableProfessor.setObjectName("tableProfessor")
        self.tableProfessor.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableProfessor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProfessor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProfessor.setHorizontalHeaderItem(2, item)
        self.tableProfessor.horizontalHeader().setStretchLastSection(True)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(80, 440, 491, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 17))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 304, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNomeCurso = QtWidgets.QLabel(self.layoutWidget)
        self.labelNomeCurso.setObjectName("labelNomeCurso")
        self.verticalLayout.addWidget(self.labelNomeCurso)
        self.linenomeProfessor = QtWidgets.QLineEdit(self.layoutWidget)
        self.linenomeProfessor.setObjectName("linenomeProfessor")
        self.verticalLayout.addWidget(self.linenomeProfessor)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelsiglaCurso = QtWidgets.QLabel(self.layoutWidget)
        self.labelsiglaCurso.setObjectName("labelsiglaCurso")
        self.verticalLayout_2.addWidget(self.labelsiglaCurso)
        self.lineMatricula = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineMatricula.setObjectName("lineMatricula")
        self.verticalLayout_2.addWidget(self.lineMatricula)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(330, 10, 151, 92))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnInserir = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnInserir.setObjectName("btnInserir")
        self.verticalLayout_4.addWidget(self.btnInserir)
        self.btnEditar = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnEditar.setObjectName("btnEditar")
        self.verticalLayout_4.addWidget(self.btnEditar)
        self.btnExcluir = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnExcluir.setObjectName("btnExcluir")
        self.verticalLayout_4.addWidget(self.btnExcluir)
        self.layoutWidget_3 = QtWidgets.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(80, 370, 481, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineBusca = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineBusca.setObjectName("lineBusca")
        self.horizontalLayout_2.addWidget(self.lineBusca)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableProfessor.horizontalHeaderItem(0)
        item.setText(_translate("Form", "idProfessor"))
        item = self.tableProfessor.horizontalHeaderItem(1)
        item.setText(_translate("Form", "nomeProfessor"))
        item = self.tableProfessor.horizontalHeaderItem(2)
        item.setText(_translate("Form", "matricula"))
        self.label.setText(_translate("Form", "Manipulação"))
        self.labelNomeCurso.setText(_translate("Form", "Nome do Professor"))
        self.labelsiglaCurso.setText(_translate("Form", "Matrícula"))
        self.btnInserir.setText(_translate("Form", "Inserir"))
        self.btnEditar.setText(_translate("Form", "Editar"))
        self.btnExcluir.setText(_translate("Form", "Excluir"))
        self.label_2.setText(_translate("Form", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

